@startuml
class model.AppState {

skinparam ClassAttributeIconSize 0
skinparam BackgroundColor #FFFFFF
skinparam PackageBackgroundColor #FAFAFA
skinparam PackageBorderColor #CCCCCC
skinparam PackageFontName "Segoe UI"
skinparam ClassFontName "Segoe UI"
skinparam ClassHeaderBackgroundColor #EBF3FC
skinparam ClassBorderColor #1F60B4
skinparam ArrowColor #555555

- {static} AppState instance
- String granularity
- String asset
- List<DataRecord> dataRecords
- List<AnomalyResult> anomalyResults
- FinancialIndicators financialIndicators
- <<Create>> AppState()
+ {static} AppState getInstance()
+ List<Instant> getInstants()
+ List<Double> getOpens()
+ List<Double> getClosures()
+ List<Double> getHighs()
+ List<Double> getLows()
+ List<Long> getVolumes()
}


class model.FinancialIndicatorsPeriods {
~ int RSIPeriod
~ int[] MACDPeriod
~ int ATRPeriod
~ int CMFPeriod
+ <<Create>> FinancialIndicatorsPeriods(String,String[],String,String)
}


class model.DataRecord {
- Instant timestamp
- double open
- double high
- double low
- double close
- long volume
}

class model.AnomalyResult {
- DataRecord dataRecord
- double score
- Map<String,Double> contributions
+ <<Create>> AnomalyResult(DataRecord,double,Map<String,Double>)
}


class model.FinancialIndicators {
- double RSI
- double MACD
- double ATR
- double CMF
}

@enduml