@startuml

skinparam ClassAttributeIconSize 0
skinparam BackgroundColor #FFFFFF
skinparam PackageBackgroundColor #FAFAFA
skinparam PackageBorderColor #CCCCCC
skinparam PackageFontName "Segoe UI"
skinparam ClassFontName "Segoe UI"
skinparam ClassHeaderBackgroundColor #EBF3FC
skinparam ClassBorderColor #1F60B4
skinparam ArrowColor #555555

class client.ApiClient {
- {static} ApiClient instance
- HttpClient httpClient
- ObjectMapper objectMapper
- <<Create>> ApiClient()
+ {static} ApiClient getInstance()
+ HttpResponse<String> sendRequest(HttpRequest.Builder)
}


@enduml